### ISSUE TITLE
Import context 

### ISSUE THREAD

**Issue by ionutt** [vyushin/file-replace-loader#19]
Is there a way to know the context of the import to know if I need to replace or not the file.

My project is an multitenant and I want to be able to replace file from core with files for a particular tenant ( that I can achive ). Because we are using Vue we can also use "extend" and I want the tenant file to extent core file. And that is something that I cannot achive because I don't know the context.

Or maybe you know another webpack feature that can achive this.

**Comment by vyushin** [comment]
Hi, @ionutt !
I published a new release that including new `replacement` function [API](https://github.com/vyushin/file-replace-loader#loader-options).
Please, update file-replace-loader and check it out!
