### ISSUE TITLE
Can this file replace loader be handle all files in folder?

### ISSUE THREAD

**Issue by EricZhaoCherryTomato** [vyushin/file-replace-loader#9]
I have a problem while using this.
I need to replace all files under src/app/exmaple/*js by override/*js
But by reading this doc, it seems it only be able to replace one file each time? Thank you inadvance

**Comment by vyushin** [comment]
@EricZhaoCherryTomato, to replace two or more files need write new rule for each one. For example:
```javascript
const { resolve } = require('path');

module.exports = {
  //...
  module: {
    rules: [{
      test: /\.config\foo.js$/,
      loader: 'file-replace-loader',
      options: {
        condition: 'if-replacement-exists',
        replacement: resolve('./foo.local.js'),
        async: true,
      }
    }, {
      test: /\.config\bar.js$/,
      loader: 'file-replace-loader',
      options: {
        condition: 'if-replacement-exists',
        replacement: resolve('./bar.local.js'),
        async: true,
      }
    }]
  }
}
```
Possible to make add new feature to multiple replacement if this is really necessary.

**Comment by vyushin** [comment]
@EricZhaoCherryTomato, please update file-replace-loader and try multiple replace
https://github.com/vyushin/file-replace-loader#multiple-replace
